### PR TITLE
Mo' betta stable

### LINKED ISSUE #50: Update the commit status API when a build fails
Just ran [this build](http://half-ogre-qed.cloudapp.net/octokit/octokit.net/builds/355) and it finishes but doesn't update the build status [here](https://github.com/octokit/octokit.net/pull/219) - it's still "waiting to hear about it"

```
STEP: Getting HEAD's SHA.
Setting SHA to 7107dd463776144e1de0c095445e1d6333694ab8.
Done
```

```
STEP: Updating GitHub build status to Failure.
The build has no SHA; skipping.
Done
```

It's probably this thingy

### PR DESCRIPTION
**Pull request by half-ogre**
QED was very fragile. _Is_ very fragile. This PR toughens her up a bit. She still has a long way to go before she's the hardened warrior I envision, but it's a start. This PR:
- Gets rid of `async` and `await`; I don't grok it well enough to get it right, and it's not really needed for a synchronous build queue. That said, I'll consider adding it back after I've had time for proper research and practice, or I'll use Rx instead.
- Is much smarter about running a process. It will now kill the process after a timeout (5 minutes for now), reports the output as it happens, reports the output in the right order, and terminates the process when it doesn't finish.
- Adds locking around saving the build output to Raven; with the switch to logging output as it happens, I was getting concurrency errors.
- Only tries to update GitHub when it actually has the info it needs (a token and a SHA)
- Lets you run QED locally with a null OAuth token, so you can test the build parts without throwing statuses at GitHub

cc @bennage, because this is going to make the merge on your F# branch a bit of a nightmare. If you want, make me a contrib on your fork and I'll fix it up. Or say the word tonight and I'll hold of merging this so we can get your stuff in first.

Fixes #50.
## To-Do
- [x] #50 
- [x] re-organize directories after adding the F# lib
- [x] move the new OWIN extensions to F#

### CODE REVIEW

**Comment by half-ogre** [comment]
@shiftkey, care to have a gander at this? I need more :eyes:.

**Comment by half-ogre** [comment]
> Keys don't usually have "Key" in them, no?

Nope, the value shouldn't have "Key" in it. Copy and paste fail. Thanks for catching that. (Also, a tip: comment on the PR's diff, not the commit. It'll show the code context, and that way it stays with the PR if I rebase.)

> Disposing a process that you received as a parameter seems wrong - cleaning up should be the caller's responsibility.

True. I consider all this stuff "internal" business as this isn't a library and not composed for re-use, but it still might confuse folks. I'll see if I can keep the responsibilities separated the way I want and still dispose in the "right" context.

> I don't believe this is necessary since you don't care to mark when the stopwatch actually terminated.

You're right, but I have a bit of OCD about stopping timers. I'll try to bring myself to axe it, but I make no promises.
- [x] remove "Key" from key const's value
- [x] put the process's dispose in the right place
- [x] maybe remove the stopwatch's stop

**Comment by half-ogre** [comment]
@dahlbyk Also, thanks for taking the :clock1: to :eyes: at this.

**Comment by dahlbyk** [comment]
> Also, a tip: comment on the PR's diff, not the commit. It'll show the code context, and that way it stays with the PR if I rebase.

Yeah, that's a small point of frustration for me TBH. For well-constructed history, as you have here, I find it much easier to review commit-by-commit ("Do these changes do what the commit message implies?") rather than look over the whole 1000-line diff. More so for review of changes pushed after an initial review. I try to switch back to the PR diff for comments, because it does show better here, but I don't always remember

I'd prefer to be able to expand the diffs within the Commits tab and comment there, so they could still be attached in the context of the PR.

**Comment by half-ogre** [comment]
> More so for review of changes pushed after an initial review.

Yeah, I'm with you. And my natural tendency is to work the same way; it's never a good sign when you have you train yourself away from your natural tendencies. Hopefully the github.com can improve this in time.

**Comment by dahlbyk** [comment]
> I'll see if I can keep the responsibilities separated the way I want and still dispose in the "right" context.

Looks like `RunProcess()` is always used in a consistent pattern:

``` csharp
var process = createProcess(
        "git.exe",
        String.Concat("fetch origin ", createFetchRefspec(build.Ref)), repositoryDirectory);

return RunProcess(process, log) == 0;
```

You should be able to switch all of those to something like this:

``` csharp
using (var process = CreateProcess(
        "git.exe",
        String.Concat("fetch origin ", createFetchRefspec(build.Ref)), repositoryDirectory))
    return RunProcess(process, log) == 0;
```

Instead, perhaps:
- Have `CreateProcess` return, and `RunProcess` accept, a `Func<Process>`.
- Merge the two functions, perhaps:
  
  ``` csharp
  return RunProcess(
        "git.exe",
        String.Concat("fetch origin ", createFetchRefspec(build.Ref)),
        repositoryDirectory,
        res => res == 0,
        log);
  ```

**Pull request merged**
